
import { db, collection, onSnapshot, query, orderBy } from './firebase.js';
const lang=localStorage.getItem('kogalym_lang')||'ru';
window.toggleLang=function(){localStorage.setItem('kogalym_lang',lang==='ru'?'en':'ru');location.reload();}
window.toggleMenu=function(){document.getElementById('mobileMenu')?.classList.toggle('open')}
function pick(o){return o?.[lang]||o?.ru||o?.en||''}
const cats={announcements:['Все','Услуги','Работа','Недвижимость','Продажа','Туризм','Бизнес'],news:['Все','Город','История','Юбилей','Спорт','Культура'],events:['Все','Концерт','Спорт','Дети','Культура','Город'],places:['Все','Кафе','Гостиница','Достопримечательность','Услуги','Маршрут']};
function fallback(t){return `<div class="visual">${(t||'К').slice(0,1).toUpperCase()}</div>`}
function card(id,col,x){const title=pick(x.title),text=pick(x.text);const img=x.imageUrl?`<img src="${x.imageUrl}" alt="">`:fallback(title);return `<article class="card news-card" data-search="${(title+' '+text+' '+(x.category||'')).toLowerCase()}">${img}${x.category?`<span class="tag">${x.category}</span>`:''}<h3>${title}</h3><p>${text.length>120?text.slice(0,120)+'...':text}</p>${x.phone?`<p><b>Тел:</b> <a href="tel:${x.phone.replace(/\D/g,'')}">${x.phone}</a></p>`:''}<a class="btn blue" href="item.html?type=${col}&id=${id}">${lang==='ru'?'Подробнее':'More'}</a></article>`}
function filters(col,id,set){const box=document.getElementById(id);if(!box)return;box.innerHTML=(cats[col]||['Все']).map((c,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${c}">${c}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');set(b.dataset.filter)})}
function render(col,listId,filterId,empty,searchId){const el=document.getElementById(listId);if(!el)return;let f='Все',docs=[],term='';const draw=()=>{let arr=f==='Все'?docs:docs.filter(d=>(d.data().category||'')===f);if(term)arr=arr.filter(d=>{const x=d.data();return ((pick(x.title)+' '+pick(x.text)+' '+(x.category||'')).toLowerCase()).includes(term)});el.innerHTML=arr.length?arr.map(d=>card(d.id,col,d.data())).join(''):`<div class="card"><p>${empty}</p></div>`};filters(col,filterId,x=>{f=x;draw()});const s=document.getElementById(searchId);if(s)s.oninput=()=>{term=s.value.toLowerCase().trim();draw()};onSnapshot(query(collection(db,col),orderBy('createdAt','desc')),snap=>{docs=snap.docs;draw()},err=>{el.innerHTML=`<div class="card"><p>Ошибка Firebase: ${err.message}</p></div>`})}
render('announcements','announcementsList','annFilters','Пока объявлений нет.','annSearch');render('news','newsList','newsFilters','Пока новостей нет.','newsSearch');render('events','eventsList','eventFilters','Пока событий нет.','eventSearch');render('places','placesList','placeFilters','Пока мест нет.','placeSearch');
